### ISSUE TITLE
Github repo out of date

### ISSUE THREAD

**Issue by owenbendavies** [openlogic/machinist-couchrest-model#4]
Currently the version of this gem on github is 1.0.2, yet on rubygems the most recent version is 1.2.0.

Would it be possible to get this updated?

Thanks,

Owen

**Comment by pezra** [comment]
Sorry for the delay. The 1.2 version is from <
https://github.com/gedwards/machinist-couchrest-model>. I haven't used
couchrest-model i a while so i am not maintaining that gem any more. Feel
free to talk to Mr Edwards. If he is not maintaining it anymore, either i
would be happy to transfer ownership of the gem to you.

Peter
